# Generated by Django 4.2.2 on 2024-09-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_paymentservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentservice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active')], default='active', max_length=50),
        ),
    ]
