# Generated by Django 4.2.2 on 2024-08-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companymanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='xrp_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='xrp_seed',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
