# Generated by Django 4.2.2 on 2024-09-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyindustry_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
