# Generated by Django 4.2.2 on 2024-07-29 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_role'),
        ('freelancers', '0002_alter_freelancer_options_alter_portfolioitem_skills_and_more'),
        ('companies', '0003_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=65)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(null=True)),
                ('location', models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On Site')], default='remote', max_length=25)),
                ('price_type', models.CharField(choices=[('per_project', 'Per Project'), ('per_hour', 'Per Hour'), ('per_week', 'Per Week'), ('per_month', 'Per Month')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'U.S Dollar'), ('GHS', 'Cedi'), ('GBP', 'British Pound'), ('NGN', 'Naira'), ('KES', 'Kenyan shilling'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar')], default='USD', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='active', max_length=25)),
                ('application_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=25)),
                ('external_apply_link', models.CharField(blank=True, max_length=100)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address')),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('tags', models.ManyToManyField(to='jobs.tag')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=25)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='freelancers.freelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.job')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
