# Generated by Django 4.2.2 on 2024-07-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='comapny',
            new_name='company',
        ),
    ]
