# Generated by Django 4.2.2 on 2024-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_comapny_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='escrow_condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='escrow_fulfillment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='escrow_sequence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('USD', 'U.S Dollar'), ('GHS', 'Cedi'), ('GBP', 'British Pound'), ('NGN', 'Naira'), ('KES', 'Kenyan shilling'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('XRP', 'Ripple')], default='XRP', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jobs.tag'),
        ),
    ]
