# Generated by Django 4.2.2 on 2024-08-16 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_escrow_condition_job_escrow_fulfillment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
