# Generated by Django 4.2.2 on 2024-08-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_skills_alter_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='job',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='role_type',
            field=models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('contract', 'Contract'), ('full_time', 'Full Time'), ('internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on-site', 'On Site'), ('hybrid', 'Hybrid')], default='remote', max_length=25),
        ),
    ]
