# Generated by Django 4.2.2 on 2024-09-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='escrow_status',
            field=models.CharField(choices=[('created', 'Created'), ('redeemed', 'Redeemed'), ('pending', 'Pending')], default='pending', max_length=25),
        ),
    ]
