# Generated by Django 4.2.2 on 2024-09-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0009_job_escrow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(null=True, upload_to='job_submissions')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='jobs.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
