# Generated by Django 4.2.2 on 2024-09-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0009_alter_service_price_type'),
        ('jobs', '0010_jobsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='jobsubmission',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_submissions', to='freelancers.freelancer'),
        ),
    ]
