# Generated by Django 4.2.2 on 2024-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=25),
        ),
    ]
