# Generated by Django 4.2.2 on 2024-08-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
