# Generated by Django 4.2.2 on 2024-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AlterField(
            model_name='service',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
