# Generated by Django 4.2.2 on 2024-08-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_alter_freelancer_options_alter_portfolioitem_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='xrp_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='xrp_seed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('USD', 'U.S Dollar'), ('GHS', 'Cedi'), ('GBP', 'British Pound'), ('NGN', 'Naira'), ('KES', 'Kenyan shilling'), ('ZAR', 'South African Rand'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('XRP', 'Ripple')], default='USD', max_length=20),
        ),
    ]
