# Generated by Django 4.2.2 on 2024-08-26 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0004_alter_freelancer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='bio',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=2),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
