# Generated by Django 4.2.2 on 2024-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_profile'),
        ('freelancers', '0005_freelancer_bio_freelancer_contact_freelancer_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='fullname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
