# Generated by Django 4.2.2 on 2024-09-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0007_alter_portfolioitem_project_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
